-- Viajamos — trip data
-- Run after RUN_IN_SUPABASE_SEEDS.sql

-- trip_days
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-22', '2026-05-22', 'Saída de Belo Horizonte', 'Voo BH → Miami e chegada com calma', 'Travel', 'Base Miami', '3024 Aviation Avenue, Miami, FL 33133', 'Noite de viagem · detalhes do voo a definir', TRUE, FALSE);
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-23', '2026-05-23', 'Primeiro dia em Miami', 'Coconut Grove, Vizcaya e pôr do sol na baía', 'Miami', 'Base Miami', '3024 Aviation Avenue, Miami, FL 33133', '29°C · Úmido e parcialmente nublado', FALSE, FALSE);
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-24', '2026-05-24', 'Little Havana + jazz', 'Calle Ocho, comida cubana e música ao vivo', 'Miami', 'Base Miami', '3024 Aviation Avenue, Miami, FL 33133', '30°C · Quente', FALSE, FALSE);
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-25', '2026-05-25', 'Arte, design e música', 'Design District, ICA Miami e Lagniappe', 'Miami', 'Base Miami', '3024 Aviation Avenue, Miami, FL 33133', '30°C · Ensolarado', FALSE, FALSE);
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-26', '2026-05-26', 'Wynwood + noite dividida', 'Murais, compras leves, jantar e eletrônica opcional', 'Miami', 'Base Miami', '3024 Aviation Avenue, Miami, FL 33133', '31°C · Quente', FALSE, FALSE);
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-27', '2026-05-27', 'Rumo às Keys', 'Manhã em Miami, estrada cênica e chegada em Islamorada', 'Islamorada', 'Base Islamorada', '82100 Overseas Highway, Islamorada, FL 33036, Estados Unidos', '29°C · Sol com chance de chuva rápida', TRUE, FALSE);
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-28', '2026-05-28', 'Água e vida marinha', 'Robbie''s, tarpons, barco com fundo de vidro e sunset', 'Islamorada', 'Base Islamorada', '82100 Overseas Highway, Islamorada, FL 33036, Estados Unidos', '30°C · Brisa de mar', FALSE, FALSE);
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-29', '2026-05-29', 'Museu, arte local e jantar na areia', 'Plano flexível entre History of Diving, Rain Barrel e Morada Bay', 'Islamorada', 'Base Islamorada', '82100 Overseas Highway, Islamorada, FL 33036, Estados Unidos', '30°C · Possível pancada à tarde', FALSE, FALSE);
INSERT INTO trip_days (id, date, title, theme, area, base_name, base_address, weather, is_travel_day, is_return_day) VALUES ('day-30', '2026-05-30', 'Fechamento da viagem', 'Manhã leve nas Keys e retorno com horários a definir', 'Travel', 'Base Islamorada', '82100 Overseas Highway, Islamorada, FL 33036, Estados Unidos', '29°C · Dia de saída', TRUE, TRUE);

-- itinerary_events
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-22-flight-placeholder', 'Saída de Belo Horizonte', 'Voo para Miami com número, horários e assentos a preencher no app.', '2026-05-22', NULL, NULL, 'night', 'Belo Horizonte / CNF', 'Belo Horizonte, MG', NULL, 'travel', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Não inserir dados sensíveis. Usar este evento como placeholder até os detalhes reais do voo.', NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-22-arrival-miami', 'Chegada em Miami e ida para a base', 'Desembarque, imigração, bagagens e Uber/carro até Coconut Grove.', '2026-05-22', '23:30', NULL, 'late_night', 'Miami International Airport', '2100 NW 42nd Ave, Miami, FL 33142', 'Miami', 'travel', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Miami+International+Airport', NULL, NULL, NULL, NULL, 'https://m.uber.com/ul/?action=setPickup&dropoff[formatted_address]=3024+Aviation+Avenue+Miami+FL+33133', 'Horário estimado até o voo ser preenchido.', NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-23-brunch-greenstreet', 'Brunch no GreenStreet', 'Primeira manhã leve em Coconut Grove, perto da base.', '2026-05-23', '10:30', '12:00', 'morning', 'GreenStreet Cafe', '3468 Main Hwy, Coconut Grove, FL 33133', 'Coconut Grove', 'food', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=GreenStreet+Cafe+Coconut+Grove', NULL, 'https://www.greenstreetcafe.com', NULL, NULL, NULL, NULL, '10:00');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-23-vizcaya', 'Vizcaya Museum & Gardens', 'Casa histórica, jardins e fotos com vista para Biscayne Bay.', '2026-05-23', '13:30', '16:30', 'afternoon', 'Vizcaya Museum & Gardens', '3251 S Miami Ave, Miami, FL 33129', 'Coconut Grove', 'museum', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Vizcaya+Museum+and+Gardens', NULL, 'https://vizcaya.org/', NULL, NULL, NULL, 'Bom plano de tarde perto da base; confirmar horários antes de sair.', NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-23-regatta', 'Pôr do sol no Regatta Grove', 'Drinks, comida e música em espaço aberto na beira da baía.', '2026-05-23', '18:00', '20:00', 'night', 'Regatta Grove', '3415 Pan American Dr, Miami, FL 33133', 'Coconut Grove', 'food', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Regatta+Grove', NULL, 'https://regattagrove.com/', NULL, NULL, NULL, NULL, '17:35');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-24-little-havana', 'Passeio por Little Havana', 'Calle Ocho, Domino Park, sorvete/café cubano e murais.', '2026-05-24', '11:00', '14:00', 'morning', 'Calle Ocho', 'SW 8th St, Miami, FL 33135', 'Little Havana', 'walk', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Calle+Ocho+Little+Havana', NULL, NULL, NULL, NULL, NULL, NULL, '10:30');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-24-versailles', 'Almoço/café no Versailles', 'Clássico cubano para sanduíches, pastelitos e café.', '2026-05-24', '14:15', NULL, 'afternoon', 'Versailles Restaurant', '3555 SW 8th St, Miami, FL 33135', 'Little Havana', 'food', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Versailles+Restaurant+Miami', NULL, 'https://www.versaillesrestaurant.com/', NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-24-ball-chain', 'Música ao vivo no Ball & Chain', 'Calle Ocho à noite com música latina/jazz e ambiente histórico.', '2026-05-24', '20:30', NULL, 'night', 'Ball & Chain', '1513 SW 8th St, Miami, FL 33135', 'Little Havana', 'music', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Ball+and+Chain+Little+Havana', NULL, 'https://ballandchainmiami.com/', NULL, NULL, NULL, 'Página oficial lista eventos de música ao vivo e horários noturnos.', '19:45');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-25-design-district', 'Miami Design District', 'Lojas, arquitetura, galerias e almoço leve na região.', '2026-05-25', '11:00', '14:00', 'morning', 'Miami Design District', '3841 NE 2nd Ave, Miami, FL 33137', 'Design District', 'shopping', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Miami+Design+District', NULL, NULL, NULL, NULL, NULL, NULL, '10:30');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-25-ica', 'ICA Miami', 'Museu compacto de arte contemporânea no Design District.', '2026-05-25', '15:00', '17:00', 'afternoon', 'ICA Miami', '61 NE 41st St, Miami, FL 33137', 'Design District', 'museum', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=ICA+Miami', NULL, 'https://icamiami.org', 'https://icamiami.org/visit', NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-25-mandolin', 'Jantar no Mandolin Aegean Bistro', 'Grego mediterrâneo em pátio charmoso no Design District.', '2026-05-25', '19:30', NULL, 'night', 'Mandolin Aegean Bistro', '4312 NE 2nd Ave, Miami, FL 33137', 'Design District', 'food', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Mandolin+Aegean+Bistro', NULL, NULL, NULL, 'https://www.mandolinmiami.com', NULL, NULL, '18:50');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-25-lagniappe-caio-sofia', 'Jazz no Lagniappe', 'Wine garden com música ao vivo das 21h à meia-noite.', '2026-05-25', '21:30', NULL, 'night', 'Lagniappe', '3425 NE 2nd Ave, Miami, FL 33137', 'Midtown', 'music', ARRAY['caio', 'sofia']::TEXT[], 'planned', 'grp-25-night', 'Caio + Sofia — jazz', 'https://maps.google.com/?q=Lagniappe+Miami', NULL, 'http://www.lagniappehouse.com/music-schedule.html', NULL, NULL, NULL, NULL, '20:55');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-25-rest-geovanin-adelaide', 'Descanso na base Miami', 'Noite leve em Coconut Grove para Geovanin e Adelaide.', '2026-05-25', '21:00', NULL, 'night', 'Base Miami', '3024 Aviation Avenue, Miami, FL 33133', NULL, 'rest', ARRAY['geovanin', 'adelaide']::TEXT[], 'planned', 'grp-25-night', 'Geovanin + Adelaide — descanso', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-26-wynwood', 'Wynwood Walls + café', 'Murais, galerias e pausa no Zak the Baker ou Salty Donut.', '2026-05-26', '10:30', '13:30', 'morning', 'Wynwood Walls', '2516 NW 2nd Ave, Miami, FL 33127', 'Wynwood', 'walk', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Wynwood+Walls', NULL, 'https://thewynwoodwalls.com/', NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-26-aventura-caio-sofia', 'Compras no Aventura Mall', 'Caio e Sofia fazem compras em shopping grande com ar-condicionado.', '2026-05-26', '15:00', '18:30', 'afternoon', 'Aventura Mall', '19501 Biscayne Blvd, Aventura, FL 33180', 'Aventura', 'shopping', ARRAY['caio', 'sofia']::TEXT[], 'planned', 'grp-26-afternoon', 'Caio + Sofia — compras', 'https://maps.google.com/?q=Aventura+Mall', NULL, 'https://aventuramall.com/', NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-26-grove-geovanin-adelaide', 'Café e leitura no Grove', 'Geovanin e Adelaide ficam perto da base para um plano leve.', '2026-05-26', '15:30', NULL, 'afternoon', 'Panther Coffee', '3400 Pan American Dr, Miami, FL 33133', 'Coconut Grove', 'food', ARRAY['geovanin', 'adelaide']::TEXT[], 'planned', 'grp-26-afternoon', 'Geovanin + Adelaide — café', 'https://maps.google.com/?q=Panther+Coffee+Coconut+Grove', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-26-family-dinner', 'Jantar em família no Jaguar', 'Jantar latino em Coconut Grove antes da noite opcional.', '2026-05-26', '20:00', NULL, 'night', 'Jaguar Ceviche Spoon', '3067 Grand Ave, Coconut Grove, FL 33133', 'Coconut Grove', 'food', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Jaguar+Ceviche+Coconut+Grove', NULL, NULL, NULL, 'https://www.jaguarmiami.com', NULL, NULL, '19:30');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-26-club-space', 'Club Space opcional', 'Eletrônica na Terrace, se houver energia e line-up interessante.', '2026-05-26', '23:30', NULL, 'late_night', 'Club Space', '34 NE 11th St, Miami, FL 33132', 'Downtown', 'music', ARRAY['caio', 'sofia']::TEXT[], 'idea', 'grp-26-late', 'Caio + Sofia — eletrônica', 'https://maps.google.com/?q=Club+Space+Miami', NULL, 'https://www.clubspace.com/', NULL, NULL, NULL, 'Comprar ingresso somente depois de confirmar line-up e disposição.', '22:45');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-27-road-to-keys', 'Estrada para Islamorada', 'Check-out em Miami, US-1/Overseas Highway e chegada à base nas Keys.', '2026-05-27', '10:00', '14:00', 'morning', 'Miami → Islamorada', '82100 Overseas Highway, Islamorada, FL 33036, Estados Unidos', 'Florida Keys', 'travel', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=82100+Overseas+Highway+Islamorada+FL+33036', NULL, NULL, NULL, NULL, NULL, NULL, '10:00');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-27-lorelei-sunset', 'Sunset no Lorelei', 'Jantar casual, happy hour e música ao vivo ao pôr do sol.', '2026-05-27', '18:00', NULL, 'night', 'Lorelei Restaurant & Cabana Bar', '96 Madeira Rd, Islamorada, FL 33036', 'Islamorada', 'food', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Lorelei+Restaurant+Islamorada', NULL, 'https://www.loreleicabanabar.com/', NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-28-robbies', 'Robbie''s: tarpons + barco', 'Alimentar tarpons e escolher glass bottom boat, kayak ou passeio ecológico.', '2026-05-28', '09:30', '13:30', 'morning', 'Robbie''s of Islamorada', '77522 Overseas Hwy, Islamorada, FL 33036', 'Islamorada', 'experience', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Robbies+of+Islamorada', NULL, 'https://robbies.com/activities.htm', NULL, NULL, NULL, NULL, '09:00');
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-28-theater-sea', 'Theater of the Sea', 'Shows contínuos de golfinhos, leões-marinhos, tartarugas e aves.', '2026-05-28', '14:30', '17:00', 'afternoon', 'Theater of the Sea', '84721 Overseas Hwy, Islamorada, FL 33036', 'Islamorada', 'experience', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Theater+of+the+Sea+Islamorada', NULL, 'https://theaterofthesea.com/attractions/hours-show-schedule/', NULL, NULL, NULL, 'Aberto 9:15-17:00; último bloco forte de shows começa às 14:00.', NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-28-square-grouper', 'Jantar no Square Grouper', 'Frutos do mar locais no Islamorada Marina.', '2026-05-28', '19:30', NULL, 'night', 'Square Grouper Islamorada', '80460 Overseas Highway, Islamorada, FL 33036', 'Islamorada', 'food', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Square+Grouper+Islamorada', NULL, 'https://www.squaregrouperislamorada.com/', NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-29-diving-museum', 'History of Diving Museum', 'Plano indoor para chuva/calor, com história do mergulho nas Keys.', '2026-05-29', '10:30', '12:00', 'morning', 'History of Diving Museum', '82990 Overseas Hwy, Islamorada, FL 33036', 'Islamorada', 'museum', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=History+of+Diving+Museum', NULL, 'https://divingmuseum.org/plan-your-visit/location-hours/', NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-29-rain-barrel', 'Rain Barrel Village', 'Arte local, lojas, jardins e foto com Betsy the Lobster.', '2026-05-29', '13:00', '15:00', 'afternoon', 'Rain Barrel Village', '86700 Overseas Hwy, Islamorada, FL 33036', 'Islamorada', 'shopping', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Rain+Barrel+Village', NULL, 'https://rainbarrelvillage.com/', NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-29-morada-bay', 'Jantar na areia no Morada Bay', 'Bistrô mediterrâneo na praia, pôr do sol e noite leve.', '2026-05-29', '18:30', NULL, 'night', 'Morada Bay Beach Cafe', '81801 Overseas Highway, Islamorada, FL 33036', 'Islamorada', 'food', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, 'https://maps.google.com/?q=Morada+Bay+Beach+Cafe', NULL, 'https://www.moradabaykeys.com/ada/dining/beach-cafe/', NULL, NULL, NULL, NULL, NULL);
INSERT INTO itinerary_events (id, title, description, date, start_time, end_time, period, location_name, address, neighborhood, category, people, status, group_id, group_label, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, uber_url, notes, leave_by) VALUES ('evt-30-checkout', 'Check-out e manhã leve nas Keys', 'Café, malas, fotos finais e horários de retorno a definir.', '2026-05-30', '09:30', NULL, 'morning', 'Base Islamorada', '82100 Overseas Highway, Islamorada, FL 33036, Estados Unidos', 'Islamorada', 'travel', ARRAY['caio', 'geovanin', 'adelaide', 'sofia']::TEXT[], 'planned', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Preencher detalhes de saída/voo quando confirmados.', NULL);

-- possible_plans
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-1', 'GreenStreet Cafe', 'Brunch clássico perto da base Miami', 'Café/brunch em Coconut Grove para começar o primeiro dia com pouco deslocamento.', 'Perto da hospedagem e fácil para ajustar o ritmo depois do voo.', 'cafe', ARRAY['morning']::event_period[], 'Miami · Coconut Grove', '3468 Main Hwy, Coconut Grove, FL 33133', 90, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=GreenStreet+Cafe+Coconut+Grove', NULL, 'https://www.greenstreetcafe.com', NULL, NULL, NULL, NULL, ARRAY['miami', 'coconut grove', 'brunch', 'perto da base']::TEXT[], 'added_to_itinerary', NULL, NULL, TRUE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-2', 'Vizcaya Museum & Gardens', 'Casa histórica e jardins', 'Museu e jardins à beira da baía, ótimo para fotos, história e um passeio bonito sem ir longe.', 'A página oficial lista horário diurno e eventos especiais de fim de maio, incluindo programações ao entardecer.', 'museum', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Coconut Grove', '3251 S Miami Ave, Miami, FL 33129', 150, 2, 'moderate', ARRAY['family', 'adelaide', 'geovanin']::best_for[], 'https://maps.google.com/?q=Vizcaya+Museum+and+Gardens', NULL, 'https://vizcaya.org/', 'https://vizcaya.org/', NULL, NULL, NULL, ARRAY['miami', 'museu', 'jardins', 'fotos', 'chuva leve']::TEXT[], 'added_to_itinerary', NULL, NULL, TRUE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-3', 'Regatta Grove', 'Drinks e comida na beira da baía', 'Espaço aberto em Coconut Grove com vista para Biscayne Bay, coquetéis, bites e música.', 'Plano fácil para pôr do sol perto da base, bom para família e para uma primeira noite sem excesso.', 'bar', ARRAY['afternoon', 'night']::event_period[], 'Miami · Coconut Grove', '3415 Pan American Dr, Miami, FL 33133', 120, 3, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Regatta+Grove', NULL, 'https://regattagrove.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'coconut grove', 'sunset', 'bar', 'perto da base']::TEXT[], 'added_to_itinerary', NULL, NULL, TRUE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-4', 'Ball & Chain', 'Música ao vivo em Little Havana', 'Casa histórica na Calle Ocho com comida cubana, coquetéis e programação frequente de música ao vivo.', 'Une jantar, bar e música em um só lugar, com identidade forte de Miami.', 'jazz', ARRAY['night', 'late_night']::event_period[], 'Miami · Little Havana', '1513 SW 8th St, Miami, FL 33135', 180, 2, 'moderate', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Ball+and+Chain+Little+Havana', NULL, 'https://ballandchainmiami.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'jazz', 'salsa', 'little havana', 'noite']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-5', 'Versailles Restaurant', 'Cubano clássico', 'Instituição de Little Havana para café cubano, pastelitos, sanduíches e pratos tradicionais.', 'Funciona bem como pausa cultural e gastronômica durante Calle Ocho.', 'restaurant', ARRAY['morning', 'afternoon', 'night', 'late_night']::event_period[], 'Miami · Little Havana', '3555 SW 8th St, Miami, FL 33135', 75, 1, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Versailles+Restaurant+Miami', NULL, 'https://www.versaillesrestaurant.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'cubano', 'café', 'late night']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-6', 'ICA Miami', 'Arte contemporânea no Design District', 'Museu compacto, bom para combinar com lojas, arquitetura e restaurantes do Design District.', 'Encaixa em uma tarde quente ou de chuva e deixa o dia cultural sem ficar pesado.', 'museum', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Design District', '61 NE 41st St, Miami, FL 33137', 120, 1, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=ICA+Miami', NULL, 'https://icamiami.org', 'https://icamiami.org/visit', NULL, NULL, NULL, ARRAY['miami', 'museu', 'design district', 'rainy day']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-7', 'Mandolin Aegean Bistro', 'Grego mediterrâneo', 'Jantar charmoso em pátio no Design District, bom para mesa em família.', 'Um dos jantares mais seguros para uma noite bonita sem virar balada.', 'restaurant', ARRAY['night']::event_period[], 'Miami · Design District', '4312 NE 2nd Ave, Miami, FL 33137', 120, 3, 'moderate', ARRAY['family', 'adelaide', 'geovanin']::best_for[], 'https://maps.google.com/?q=Mandolin+Aegean+Bistro', NULL, 'https://www.mandolinmiami.com', NULL, 'https://www.mandolinmiami.com', NULL, NULL, ARRAY['miami', 'jantar', 'reserva', 'grego']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-8', 'Lagniappe', 'Wine garden com música ao vivo', 'Pátio descontraído em Midtown com música ao vivo diariamente das 21h à meia-noite.', 'Boa saída para Caio e Sofia depois do jantar, com vibe musical sem ser club.', 'jazz', ARRAY['night']::event_period[], 'Miami · Midtown', '3425 NE 2nd Ave, Miami, FL 33137', 150, 2, 'moderate', ARRAY['caio', 'sofia', 'caio_sofia']::best_for[], 'https://maps.google.com/?q=Lagniappe+Miami', NULL, 'http://www.lagniappehouse.com/music-schedule.html', NULL, NULL, NULL, NULL, ARRAY['miami', 'jazz', 'vinho', 'música ao vivo']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-9', 'Genuine Jazz Night', 'Jazz no Michael''s Genuine', 'Noite de jazz no Design District com comida e coquetéis em Michael''s Genuine.', 'Opção musical mais confortável e gastronômica para quarta à noite, se a data encaixar.', 'jazz', ARRAY['night']::event_period[], 'Miami · Design District', '130 NE 40th St, Miami, FL 33137', 150, 3, 'light', ARRAY['family', 'adults']::best_for[], 'https://maps.google.com/?q=Michael''s+Genuine+Food+%26+Drink', NULL, 'https://www.miamidesigndistrict.com/event/2889/genuine-jazz-night/', NULL, NULL, NULL, NULL, ARRAY['miami', 'jazz', 'design district', 'quarta']::TEXT[], 'shortlisted', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-10', 'Wynwood Walls', 'Arte urbana e fotos', 'Murais, galerias e caminhada curta com cafés próximos.', 'Bom para Caio e Sofia, mas ainda funciona para todos se for pela manhã.', 'gallery', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Wynwood', '2516 NW 2nd Ave, Miami, FL 33127', 120, 2, 'moderate', ARRAY['family', 'caio', 'sofia', 'caio_sofia']::best_for[], 'https://maps.google.com/?q=Wynwood+Walls', NULL, 'https://thewynwoodwalls.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'arte urbana', 'fotos', 'wynwood']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-11', 'Zak the Baker', 'Padaria no Wynwood', 'Padaria/café para encaixar antes ou depois de Wynwood Walls.', 'Pausa rápida, boa comida e deslocamento simples dentro de Wynwood.', 'cafe', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Wynwood', '295 NW 26th St, Miami, FL 33127', 45, 2, 'light', ARRAY['family', 'caio']::best_for[], 'https://maps.google.com/?q=Zak+the+Baker', NULL, 'https://zakthebaker.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'café', 'padaria', 'wynwood']::TEXT[], 'shortlisted', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-12', 'Aventura Mall', 'Shopping premium', 'Shopping grande, com ar-condicionado e muitas marcas internacionais.', 'Plano forte para calor/chuva e compras de Caio + Sofia.', 'shopping', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Aventura', '19501 Biscayne Blvd, Aventura, FL 33180', 240, 3, 'moderate', ARRAY['family', 'sofia', 'caio_sofia']::best_for[], 'https://maps.google.com/?q=Aventura+Mall', NULL, 'https://aventuramall.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'compras', 'shopping', 'rainy day']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-13', 'Club Space', 'Eletrônica e maratona de pista', 'Club conhecido pela Terrace e por noites/madrugadas longas de eletrônica.', 'Opção principal de eletrônico se Caio e Sofia quiserem uma noite intensa.', 'electronic_music', ARRAY['late_night']::event_period[], 'Miami · Downtown', '34 NE 11th St, Miami, FL 33132', 300, 3, 'intense', ARRAY['caio', 'sofia', 'caio_sofia']::best_for[], 'https://maps.google.com/?q=Club+Space+Miami', NULL, 'https://www.clubspace.com/', 'https://www.clubspace.com/', NULL, NULL, NULL, ARRAY['miami', 'eletrônica', 'late night', 'downtown']::TEXT[], 'shortlisted', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-14', 'PAMM', 'Museu à beira da baía', 'Museu de arte moderna e contemporânea com boa estrutura indoor.', 'Plano B elegante para chuva ou calor forte, com vista para Biscayne Bay.', 'rainy_day', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Downtown', '1103 Biscayne Blvd, Miami, FL 33132', 150, 2, 'light', ARRAY['family', 'adelaide', 'geovanin']::best_for[], 'https://maps.google.com/?q=Perez+Art+Museum+Miami', NULL, 'https://www.pamm.org/en/visit', 'https://www.pamm.org/en/visit', NULL, NULL, NULL, ARRAY['miami', 'museu', 'chuva', 'indoor']::TEXT[], 'candidate', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-15', 'Trader Joe''s Coconut Grove', 'Mercado perto da base', 'Mercado para snacks, café da manhã, água e itens práticos.', 'Resolve a logística da casa em 30-45 minutos.', 'nearby', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Coconut Grove', '2990 McFarlane Rd, Miami, FL 33133', 45, 1, 'light', ARRAY['family', 'adults']::best_for[], 'https://maps.google.com/?q=Trader+Joes+Coconut+Grove', NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['miami', 'mercado', 'perto da base', 'essencial']::TEXT[], 'candidate', NULL, NULL, TRUE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-16', 'Robbie''s of Islamorada', 'Tarpons, passeios de barco e esportes aquáticos', 'Base de atividades nas Keys com tarpon feeding, glass bottom boat, kayak, paddle, snorkeling e eco tours.', 'Concentra várias experiências típicas de Islamorada em um só lugar.', 'experience', ARRAY['morning', 'afternoon']::event_period[], 'Islamorada', '77522 Overseas Hwy, Islamorada, FL 33036', 240, 2, 'moderate', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Robbies+of+Islamorada', NULL, 'https://robbies.com/activities.htm', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'tarpon', 'barco', 'água']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-17', 'Theater of the Sea', 'Shows marinhos em Islamorada', 'Parque com shows contínuos de tartarugas, aves, golfinhos, leões-marinhos, peixes, tubarões e raias.', 'Atividade familiar estruturada, boa quando não quiser depender de barco/clima perfeito.', 'experience', ARRAY['morning', 'afternoon']::event_period[], 'Islamorada', '84721 Overseas Hwy, Islamorada, FL 33036', 180, 3, 'moderate', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Theater+of+the+Sea+Islamorada', NULL, 'https://theaterofthesea.com/attractions/hours-show-schedule/', 'https://theaterofthesea.com/', NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'animais', 'família']::TEXT[], 'shortlisted', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-18', 'Square Grouper Islamorada', 'Frutos do mar locais', 'Restaurante no Islamorada Marina com peixe local, coquetéis e ambiente mais arrumado.', 'Jantar de frutos do mar forte para uma noite nas Keys.', 'restaurant', ARRAY['afternoon', 'night']::event_period[], 'Islamorada', '80460 Overseas Highway, Islamorada, FL 33036', 120, 3, 'light', ARRAY['family', 'adults']::best_for[], 'https://maps.google.com/?q=Square+Grouper+Islamorada', NULL, 'https://www.squaregrouperislamorada.com/', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'frutos do mar', 'jantar']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-19', 'Lorelei Restaurant & Cabana Bar', 'Sunset e música ao vivo', 'Restaurante/bar na baía, conhecido por pôr do sol, happy hour e música ao vivo.', 'Primeira noite ideal em Islamorada: simples, bonito e com cara de Keys.', 'bar', ARRAY['afternoon', 'night']::event_period[], 'Islamorada', '96 Madeira Rd, Islamorada, FL 33036', 150, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Lorelei+Restaurant+Islamorada', NULL, 'https://www.loreleicabanabar.com/', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'sunset', 'música ao vivo', 'bar']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-20', 'Morada Bay Beach Cafe', 'Jantar na areia', 'Bistrô mediterrâneo/americano em praia com palmeiras, vista para a água e pôr do sol.', 'Jantar mais cênico da parte Islamorada, bom para fechar a viagem.', 'restaurant', ARRAY['afternoon', 'night']::event_period[], 'Islamorada', '81801 Overseas Highway, Islamorada, FL 33036', 150, 3, 'light', ARRAY['family', 'adelaide', 'geovanin']::best_for[], 'https://maps.google.com/?q=Morada+Bay+Beach+Cafe', NULL, 'https://www.moradabaykeys.com/ada/dining/beach-cafe/', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'sunset', 'jantar', 'praia']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-21', 'History of Diving Museum', 'Plano indoor nas Keys', 'Museu sobre a história do mergulho, aberto diariamente e útil para chuva ou calor forte.', 'Plano de 60-90 minutos, perto da base Islamorada, sem depender de mar calmo.', 'rainy_day', ARRAY['morning', 'afternoon']::event_period[], 'Islamorada', '82990 Overseas Hwy, Islamorada, FL 33036', 90, 1, 'light', ARRAY['family', 'adults']::best_for[], 'https://maps.google.com/?q=History+of+Diving+Museum', NULL, 'https://divingmuseum.org/plan-your-visit/location-hours/', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'museu', 'chuva', 'indoor']::TEXT[], 'added_to_itinerary', NULL, NULL, TRUE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-22', 'Rain Barrel Village', 'Arte local e Betsy the Lobster', 'Complexo aberto com lojas, galerias, jardins e a famosa escultura gigante de lagosta.', 'Pausa leve para compras e fotos, boa para tarde sem pressa.', 'shopping', ARRAY['morning', 'afternoon']::event_period[], 'Islamorada', '86700 Overseas Hwy, Islamorada, FL 33036', 90, 1, 'light', ARRAY['family', 'sofia', 'adelaide']::best_for[], 'https://maps.google.com/?q=Rain+Barrel+Village', NULL, 'https://rainbarrelvillage.com/', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'compras', 'arte', 'fotos']::TEXT[], 'added_to_itinerary', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-23', 'Florida Keys Brewing Co.', 'Cervejaria local', 'Cervejaria de Islamorada para fim de tarde casual, antes ou depois do jantar.', 'Boa opção de bar local quando a família quiser algo simples e perto.', 'bar', ARRAY['afternoon', 'night']::event_period[], 'Islamorada', '81611 Old Hwy, Islamorada, FL 33036', 90, 2, 'light', ARRAY['adults', 'caio', 'sofia']::best_for[], 'https://maps.google.com/?q=Florida+Keys+Brewing+Company', NULL, 'https://www.floridakeysbrewingco.com/', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'cerveja', 'bar', 'fim de tarde']::TEXT[], 'candidate', NULL, NULL, TRUE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-24', 'Kayak até Indian Key', 'Natureza e manguezais', 'Aluguel/guia de kayak ou paddle para explorar águas rasas e manguezais saindo de Robbie''s.', 'Experiência Keys mais ativa, ótima se o clima e o vento estiverem bons.', 'experience', ARRAY['morning']::event_period[], 'Islamorada', '77522 Overseas Hwy, Islamorada, FL 33036', 180, 2, 'intense', ARRAY['caio', 'sofia', 'caio_sofia']::best_for[], 'https://maps.google.com/?q=Robbies+Kayak+Shack+Islamorada', NULL, 'https://robbies.com/activities.htm', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'kayak', 'outdoors', 'ativo']::TEXT[], 'candidate', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-25', 'Glass Bottom Boat', 'Recife sem molhar todo mundo', 'Passeio de barco com fundo de vidro para ver recifes como Cheeca Rocks e Alligator Reef.', 'Alternativa mais confortável ao snorkel para a família inteira.', 'experience', ARRAY['morning', 'afternoon']::event_period[], 'Islamorada', '77522 Overseas Hwy, Islamorada, FL 33036', 120, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Robbies+Glass+Bottom+Boat+Islamorada', NULL, 'https://robbies.com/activities.htm', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'barco', 'recife', 'família']::TEXT[], 'shortlisted', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-26', 'CocoWalk', 'Perto da base Miami', 'Shopping pequeno e área de restaurantes em Coconut Grove para compras leves ou plano rápido.', 'Útil quando alguém quiser sair sem atravessar a cidade.', 'nearby', ARRAY['morning', 'afternoon', 'night']::event_period[], 'Miami · Coconut Grove', '3015 Grand Ave, Coconut Grove, FL 33133', 90, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=CocoWalk+Coconut+Grove', NULL, 'https://cocowalk.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'nearby', 'coconut grove', 'compras']::TEXT[], 'candidate', NULL, NULL, TRUE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-27', 'Sweet Liberty', 'Coquetelaria em Miami Beach', 'Bar para coquetéis premiados e comida tarde da noite, bom se a noite for para Miami Beach.', 'Alternativa menos intensa que club, mas ainda com energia de noite.', 'late_night', ARRAY['night', 'late_night']::event_period[], 'Miami · Miami Beach', '237 20th St Suite B, Miami Beach, FL 33139', 120, 3, 'moderate', ARRAY['caio', 'sofia', 'caio_sofia']::best_for[], 'https://maps.google.com/?q=Sweet+Liberty+Miami+Beach', NULL, 'https://www.mysweetliberty.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'bar', 'late night', 'coquetéis']::TEXT[], 'candidate', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-28', 'Bayside Marketplace', 'Shopping e baía', 'Centro comercial com lojas, restaurantes e passeios de barco no Downtown.', 'Plano flexível para chuva, compras rápidas ou espera entre compromissos.', 'rainy_day', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Downtown', '401 Biscayne Blvd, Miami, FL 33132', 120, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Bayside+Marketplace', NULL, 'https://www.baysidemarketplace.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'shopping', 'chuva', 'downtown']::TEXT[], 'candidate', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-29', 'Key Biscayne / Crandon Park', 'Praia mais tranquila', 'Praia e passeio leve ao sul de Miami, mais calmo que South Beach.', 'Bom se quiserem natureza sem ir para as Keys ainda.', 'walk', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Key Biscayne', '6747 Crandon Blvd, Key Biscayne, FL 33149', 180, 1, 'light', ARRAY['family', 'adelaide', 'geovanin']::best_for[], 'https://maps.google.com/?q=Crandon+Park+Beach', NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['miami', 'praia', 'outdoors', 'família']::TEXT[], 'candidate', NULL, NULL, FALSE);
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-30', 'Tasting Florida Keys History', 'História + comidas das Keys', 'Experiência em Robbie''s com historiador local, conch chowder, fritters, rumrunner e key lime pie.', 'Opção bem específica de Islamorada para segunda/quinta, combinando cultura e comida.', 'experience', ARRAY['morning', 'afternoon']::event_period[], 'Islamorada', '77522 Overseas Hwy, Islamorada, FL 33036', 60, 2, 'light', ARRAY['family', 'adults']::best_for[], 'https://maps.google.com/?q=Robbies+of+Islamorada', NULL, 'https://robbies.com/activities.htm', 'https://fareharbor.com/embeds/book/hungrytarpon/?full-items=yes', NULL, NULL, NULL, ARRAY['islamorada', 'keys', 'história', 'comida', 'quinta']::TEXT[], 'shortlisted', NULL, NULL, FALSE);

-- day_alternative_plans
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-22-delay', 'day-22', 'late_start', 'Chegada tarde sem compromisso', 'Ir direto para a base Miami, deixar compras e restaurantes para a manhã seguinte', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-23-rain', 'day-23', 'rain', 'Coconut Grove indoor', 'CocoWalk, Books & Books, mercado e jantar perto da base Miami', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-24-tired', 'day-24', 'tired', 'Little Havana mais curto', 'Fazer Versailles + Ball & Chain e pular a caminhada longa pela Calle Ocho', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-25-rain', 'day-25', 'rain', 'PAMM + shopping indoor', 'Pérez Art Museum, Bayside Marketplace e jantar coberto', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-25-energy', 'day-25', 'extra_energy', 'Noite extra', 'Lagniappe para Caio e Sofia; Geovanin e Adelaide descansam na base', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-26-hot', 'day-26', 'too_hot', 'Shopping com ar-condicionado', 'Trocar Wynwood por Aventura Mall ou Bayside Marketplace', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-27-late', 'day-27', 'late_start', 'Chegada direta em Islamorada', 'Pular paradas na estrada e ir direto para a base; Lorelei fica só se houver energia', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-28-wind', 'day-28', 'too_hot', 'Menos água, mais shows', 'Se vento/mar atrapalhar Robbie''s, priorizar Theater of the Sea e jantar cedo', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-29-rain', 'day-29', 'rain', 'Islamorada indoor', 'History of Diving Museum, almoço longo e compras cobertas/rápidas no Rain Barrel', ARRAY[]::TEXT[]);
INSERT INTO day_alternative_plans (id, day_id, trigger, title, description, plan_item_ids) VALUES ('alt-30-tired', 'day-30', 'tired', 'Saída sem paradas', 'Café simples, malas e deslocamento direto conforme horário de retorno', ARRAY[]::TEXT[]);

-- essential_places
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-lodging-miami', 'Base Miami — Coconut Grove', 'lodging', '3024 Aviation Avenue, Miami, FL 33133', 'Miami', 'Base Miami', 'Base da primeira parte da viagem, de 22/05 a 27/05.', 'https://maps.google.com/?q=3024+Aviation+Avenue+Miami+FL+33133', 'https://maps.apple.com/?address=3024+Aviation+Avenue,Miami,FL+33133', 'https://m.uber.com/ul/?action=setPickup&dropoff[formatted_address]=3024+Aviation+Avenue+Miami');
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-lodging-islamorada', 'Base Islamorada', 'lodging', '82100 Overseas Highway, Islamorada, FL 33036, Estados Unidos', 'Islamorada', 'Base Islamorada', 'Base da segunda parte da viagem, de 27/05 a 30/05.', 'https://maps.google.com/?q=82100+Overseas+Highway+Islamorada+FL+33036', 'https://maps.apple.com/?address=82100+Overseas+Highway,Islamorada,FL+33036', 'https://m.uber.com/ul/?action=setPickup&dropoff[formatted_address]=82100+Overseas+Highway+Islamorada+FL+33036');
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-airport', 'Miami International Airport (MIA)', 'airport', '2100 NW 42nd Ave, Miami, FL 33142', 'Travel', 'Aeroporto', 'Chegada/saída internacional; detalhes de voo serão preenchidos no app.', 'https://maps.google.com/?q=Miami+International+Airport', NULL, 'https://m.uber.com/ul/?action=setPickup&dropoff[formatted_address]=Miami+International+Airport');
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-cnf', 'Aeroporto de Belo Horizonte / Confins (CNF)', 'airport', 'Rodovia LMG 800, Confins, MG', 'Travel', 'Saída BH', 'Ponto de partida em 22/05; preencher terminal/companhia quando confirmado.', 'https://maps.google.com/?q=Aeroporto+Internacional+de+Belo+Horizonte+Confins', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-pharmacy', 'CVS Pharmacy', 'pharmacy', '3101 Grand Ave, Coconut Grove, FL 33133', 'Miami', 'Base Miami', 'Remédios, protetor solar, itens de farmácia.', 'https://maps.google.com/?q=CVS+Coconut+Grove+3101+Grand+Ave', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-market-miami', 'Trader Joe''s Coconut Grove', 'market', '2990 McFarlane Rd, Miami, FL 33133', 'Miami', 'Base Miami', 'Mercado principal perto de casa.', 'https://maps.google.com/?q=Trader+Joes+Coconut+Grove', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-market-islamorada', 'Publix Super Market at Islamorada', 'market', '83268 Overseas Hwy, Islamorada, FL 33036', 'Islamorada', 'Base Islamorada', 'Mercado para água, café da manhã e itens de praia nas Keys.', 'https://maps.google.com/?q=Publix+Islamorada', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-hospital', 'Baptist Hospital', 'hospital', '8900 N Kendall Dr, Miami, FL 33176', 'Miami', 'Emergência Miami', 'Emergência — ligar 911 nos EUA.', 'https://maps.google.com/?q=Baptist+Hospital+Miami', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-hospital-keys', 'Fishermen''s Community Hospital', 'hospital', '3301 Overseas Hwy, Marathon, FL 33050', 'Islamorada', 'Emergência Keys', 'Referência hospitalar na região das Keys; em emergência, ligar 911.', 'https://maps.google.com/?q=Fishermen%27s+Community+Hospital+Marathon', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-shopping', 'CocoWalk', 'shopping', '3015 Grand Ave, Coconut Grove, FL 33133', 'Miami', 'Base Miami', 'Shopping pequeno a pé do Grove.', 'https://maps.google.com/?q=CocoWalk+Coconut+Grove', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-consulate', 'Consulado Geral do Brasil', 'consulate', '80 SW 8th St, Miami, FL 33130', 'Miami', 'Documentos', 'Emergências consulares.', 'https://maps.google.com/?q=Brazilian+Consulate+Miami', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-meeting-miami', 'Ponto de encontro Miami — CocoWalk', 'meeting_point', '3015 Grand Ave, Coconut Grove, FL 33133', 'Miami', 'Base Miami', 'Combinado da família se alguém se perder.', 'https://maps.google.com/?q=CocoWalk+Coconut+Grove', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-meeting-islamorada', 'Ponto de encontro Islamorada — Rain Barrel Village', 'meeting_point', '86700 Overseas Hwy, Islamorada, FL 33036', 'Islamorada', 'Base Islamorada', 'Ponto fácil de reconhecer por causa da Betsy the Lobster.', 'https://maps.google.com/?q=Rain+Barrel+Village', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-apple', 'Apple Store — Lincoln Road', 'shopping', '1021 Lincoln Rd, Miami Beach, FL 33139', 'Miami', 'Suporte', 'Suporte Apple se precisar.', 'https://maps.google.com/?q=Apple+Store+Lincoln+Road', NULL, NULL);
INSERT INTO essential_places (id, name, type, address, area, base_name, notes, google_maps_url, apple_maps_url, uber_url) VALUES ('ep-robbies', 'Robbie''s of Islamorada', 'meeting_point', '77522 Overseas Hwy, Islamorada, FL 33036', 'Islamorada', 'Atividades Keys', 'Tarpons, passeios de barco, kayak, snorkeling e alimentação.', 'https://maps.google.com/?q=Robbies+of+Islamorada', NULL, NULL);

-- travel_documents
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-flights', 'Detalhes dos voos — a preencher', 'flight', NULL, 'Não há dados sensíveis salvos. Preencher companhia, número do voo, horários e assentos no app.');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-lodging-miami', 'Hospedagem Miami — Coconut Grove', 'lodging', NULL, 'Base 22/05-27/05. Endereço: 3024 Aviation Avenue, Miami, FL 33133.');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-lodging-islamorada', 'Hospedagem Islamorada', 'lodging', NULL, 'Base 27/05-30/05. Endereço: 82100 Overseas Highway, Islamorada, FL 33036, Estados Unidos.');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-robbies', 'Robbie''s of Islamorada — atividades', 'ticket', 'https://robbies.com/activities.htm', 'Escolher entre tarpon feeding, glass bottom boat, kayak/paddle, snorkeling ou eco tour.');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-mandolin', 'Reserva Mandolin — 25/05', 'reservation', 'https://www.mandolinmiami.com', 'Mesa para 4 pessoas; confirmar horário.');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-club-space', 'Club Space — line-up/ingresso opcional', 'ticket', 'https://www.clubspace.com/', 'Comprar somente se Caio e Sofia confirmarem disposição e line-up.');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-morada-bay', 'Morada Bay Beach Cafe — 29/05', 'reservation', 'https://www.moradabaykeys.com/ada/dining/beach-cafe/', 'Restaurante na areia; confirmar política de reserva.');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-insurance', 'Seguro viagem', 'insurance', NULL, 'Apólice no e-mail — cobertura médica internacional');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-ica', 'ICA Miami — visita', 'ticket', 'https://icamiami.org/visit', 'Entrada gratuita, sem reserva necessária');
INSERT INTO travel_documents (id, title, type, url, notes) VALUES ('doc-theater-sea', 'Theater of the Sea — horários', 'ticket', 'https://theaterofthesea.com/attractions/hours-show-schedule/', 'Shows contínuos; chegar antes das 14h para aproveitar melhor.');

-- trip_tasks
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-1', 'Preencher detalhes do voo de ida BH → Miami', '2026-05-22', 'evt-22-flight-placeholder', 'caio', 'open', 'high');
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-2', 'Confirmar check-in e instruções da base Miami', '2026-05-22', 'evt-22-arrival-miami', 'geovanin', 'open', 'high');
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-3', 'Reservar Mandolin ou alternativa no Design District', '2026-05-25', 'evt-25-mandolin', 'adelaide', 'open', 'medium');
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-4', 'Conferir line-up e ingresso do Club Space', '2026-05-26', 'evt-26-club-space', 'caio', 'open', 'medium');
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-5', 'Confirmar transporte Miami → Islamorada', '2026-05-27', 'evt-27-road-to-keys', NULL, 'open', 'high');
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-6', 'Reservar/checar atividade principal em Robbie''s', '2026-05-28', 'evt-28-robbies', 'sofia', 'open', 'medium');
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-7', 'Confirmar jantar no Morada Bay ou Square Grouper', '2026-05-28', 'evt-29-morada-bay', 'adelaide', 'open', 'medium');
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-8', 'Preencher detalhes de retorno/saída em 30/05', '2026-05-30', 'evt-30-checkout', 'caio', 'open', 'high');
INSERT INTO trip_tasks (id, title, due_date, related_plan_id, assigned_to, status, priority) VALUES ('task-9', 'Comprar eSIM / chip de dados EUA', '2026-05-22', NULL, NULL, 'open', 'high');

-- night_events
INSERT INTO night_events (id, date, type, title, venue, neighborhood, start_time, end_time, price_info, dress_code, intensity, buy_ahead, google_maps_url, apple_maps_url, website_url, ticket_url, uber_url, status, notes) VALUES ('ne-1', '2026-05-24', 'jazz', 'Música ao vivo — Ball & Chain', 'Ball & Chain', 'Little Havana', '20:30', '01:00', 'Confirmar evento/entrada no site', 'Casual elegante', 'moderate', FALSE, 'https://maps.google.com/?q=Ball+and+Chain+Little+Havana', NULL, 'https://ballandchainmiami.com/', NULL, NULL, 'added_to_itinerary', NULL);
INSERT INTO night_events (id, date, type, title, venue, neighborhood, start_time, end_time, price_info, dress_code, intensity, buy_ahead, google_maps_url, apple_maps_url, website_url, ticket_url, uber_url, status, notes) VALUES ('ne-2', '2026-05-23', 'bar', 'Sunset — Regatta Grove', 'Regatta Grove', 'Coconut Grove', '18:00', NULL, 'Sem entrada; consumo no local', NULL, 'light', FALSE, 'https://maps.google.com/?q=Regatta+Grove', NULL, 'https://regattagrove.com/', NULL, NULL, 'added_to_itinerary', NULL);
INSERT INTO night_events (id, date, type, title, venue, neighborhood, start_time, end_time, price_info, dress_code, intensity, buy_ahead, google_maps_url, apple_maps_url, website_url, ticket_url, uber_url, status, notes) VALUES ('ne-3', '2026-05-25', 'jazz', 'John Yarling — Lagniappe', 'Lagniappe', 'Midtown', '21:30', '00:00', 'Sem reserva; consumo no local', 'Casual', 'moderate', FALSE, 'https://maps.google.com/?q=Lagniappe+Miami', NULL, 'http://www.lagniappehouse.com/music-schedule.html', NULL, NULL, 'added_to_itinerary', 'Programação oficial lista música ao vivo todas as noites, 21h-0h.');
INSERT INTO night_events (id, date, type, title, venue, neighborhood, start_time, end_time, price_info, dress_code, intensity, buy_ahead, google_maps_url, apple_maps_url, website_url, ticket_url, uber_url, status, notes) VALUES ('ne-4', '2026-05-26', 'jazz', 'Lemon City Trio — Lagniappe', 'Lagniappe', 'Midtown', '21:00', '00:00', 'Sem reserva; consumo no local', NULL, 'moderate', FALSE, 'https://maps.google.com/?q=Lagniappe+Miami', NULL, 'http://www.lagniappehouse.com/music-schedule.html', NULL, NULL, 'candidate', NULL);
INSERT INTO night_events (id, date, type, title, venue, neighborhood, start_time, end_time, price_info, dress_code, intensity, buy_ahead, google_maps_url, apple_maps_url, website_url, ticket_url, uber_url, status, notes) VALUES ('ne-5', '2026-05-26', 'electronic', 'Noite opcional — Club Space', 'Club Space', 'Downtown', '23:30', '06:00', 'Comprar só após confirmar line-up', 'Casual / clubwear', 'intense', FALSE, 'https://maps.google.com/?q=Club+Space+Miami', NULL, 'https://www.clubspace.com/', 'https://www.clubspace.com/', NULL, 'shortlisted', NULL);
INSERT INTO night_events (id, date, type, title, venue, neighborhood, start_time, end_time, price_info, dress_code, intensity, buy_ahead, google_maps_url, apple_maps_url, website_url, ticket_url, uber_url, status, notes) VALUES ('ne-6', '2026-05-27', 'bar', 'Sunset — Lorelei', 'Lorelei Restaurant & Cabana Bar', 'Islamorada', '18:00', NULL, 'Happy hour e consumo no local', NULL, 'light', FALSE, 'https://maps.google.com/?q=Lorelei+Restaurant+Islamorada', NULL, 'https://www.loreleicabanabar.com/', NULL, NULL, 'added_to_itinerary', NULL);
INSERT INTO night_events (id, date, type, title, venue, neighborhood, start_time, end_time, price_info, dress_code, intensity, buy_ahead, google_maps_url, apple_maps_url, website_url, ticket_url, uber_url, status, notes) VALUES ('ne-7', '2026-05-28', 'bar', 'Cerveja local — Florida Keys Brewing Co.', 'Florida Keys Brewing Co.', 'Islamorada', '17:30', NULL, 'Consumo no local', NULL, 'light', FALSE, 'https://maps.google.com/?q=Florida+Keys+Brewing+Company', NULL, 'https://www.floridakeysbrewingco.com/', NULL, NULL, 'candidate', NULL);
INSERT INTO night_events (id, date, type, title, venue, neighborhood, start_time, end_time, price_info, dress_code, intensity, buy_ahead, google_maps_url, apple_maps_url, website_url, ticket_url, uber_url, status, notes) VALUES ('ne-8', '2026-05-29', 'bar', 'Jantar sunset — Morada Bay', 'Morada Bay Beach Cafe', 'Islamorada', '18:30', NULL, 'Jantar na areia; reservas limitadas', NULL, 'light', FALSE, 'https://maps.google.com/?q=Morada+Bay+Beach+Cafe', NULL, 'https://www.moradabaykeys.com/ada/dining/beach-cafe/', NULL, NULL, 'added_to_itinerary', NULL);

-- flights
INSERT INTO flights (id, passenger_id, passenger_name, route, "from", "to", flight_number, seat, terminal, gate, boarding_time, departure_time, arrival_time, date, status, confirmation_code) VALUES ('flt-caio-out', 'caio', 'CAIO', 'Belo Horizonte → Miami', 'BHZ/CNF', 'MIA', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', '2026-05-22', 'pending', NULL);
INSERT INTO flights (id, passenger_id, passenger_name, route, "from", "to", flight_number, seat, terminal, gate, boarding_time, departure_time, arrival_time, date, status, confirmation_code) VALUES ('flt-geovanin-out', 'geovanin', 'GEOVANIN', 'Belo Horizonte → Miami', 'BHZ/CNF', 'MIA', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', '2026-05-22', 'pending', NULL);
INSERT INTO flights (id, passenger_id, passenger_name, route, "from", "to", flight_number, seat, terminal, gate, boarding_time, departure_time, arrival_time, date, status, confirmation_code) VALUES ('flt-adelaide-out', 'adelaide', 'ADELAIDE', 'Belo Horizonte → Miami', 'BHZ/CNF', 'MIA', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', '2026-05-22', 'pending', NULL);
INSERT INTO flights (id, passenger_id, passenger_name, route, "from", "to", flight_number, seat, terminal, gate, boarding_time, departure_time, arrival_time, date, status, confirmation_code) VALUES ('flt-sofia-out', 'sofia', 'SOFIA', 'Belo Horizonte → Miami', 'BHZ/CNF', 'MIA', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', '2026-05-22', 'pending', NULL);
INSERT INTO flights (id, passenger_id, passenger_name, route, "from", "to", flight_number, seat, terminal, gate, boarding_time, departure_time, arrival_time, date, status, confirmation_code) VALUES ('flt-caio-ret', 'caio', 'CAIO', 'Miami → Belo Horizonte', 'MIA', 'BHZ/CNF', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', '2026-05-30', 'pending', NULL);
INSERT INTO flights (id, passenger_id, passenger_name, route, "from", "to", flight_number, seat, terminal, gate, boarding_time, departure_time, arrival_time, date, status, confirmation_code) VALUES ('flt-geovanin-ret', 'geovanin', 'GEOVANIN', 'Miami → Belo Horizonte', 'MIA', 'BHZ/CNF', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', '2026-05-30', 'pending', NULL);
INSERT INTO flights (id, passenger_id, passenger_name, route, "from", "to", flight_number, seat, terminal, gate, boarding_time, departure_time, arrival_time, date, status, confirmation_code) VALUES ('flt-adelaide-ret', 'adelaide', 'ADELAIDE', 'Miami → Belo Horizonte', 'MIA', 'BHZ/CNF', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', '2026-05-30', 'pending', NULL);
INSERT INTO flights (id, passenger_id, passenger_name, route, "from", "to", flight_number, seat, terminal, gate, boarding_time, departure_time, arrival_time, date, status, confirmation_code) VALUES ('flt-sofia-ret', 'sofia', 'SOFIA', 'Miami → Belo Horizonte', 'MIA', 'BHZ/CNF', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', 'A definir', '2026-05-30', 'pending', NULL);

-- memories
INSERT INTO memories (id, day_id, date, best_moment, best_food, favorite_place, rating, notes, photo_url) VALUES ('mem-1', 'day-23', '2026-05-23', '', '', '', 0, '', NULL);
INSERT INTO memories (id, day_id, date, best_moment, best_food, favorite_place, rating, notes, photo_url) VALUES ('mem-2', 'day-28', '2026-05-28', '', '', '', 0, '', NULL);

-- travel_timeline_items
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-dep-1', 'A definir', 'Sair para o aeroporto em Belo Horizonte', '2026-05-22', TRUE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-dep-2', 'A definir', 'Check-in e despacho de bagagem', '2026-05-22', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-dep-3', 'A definir', 'Embarque para Miami', '2026-05-22', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-dep-4', 'A definir', 'Chegada em Miami, imigração e bagagem', '2026-05-22', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-dep-5', 'A definir', 'Uber/carro até a base Miami', '2026-05-22', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-keys-1', '09:30', 'Organizar malas e check-out da base Miami', '2026-05-27', TRUE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-keys-2', '10:00', 'Sair de Miami rumo a Islamorada', '2026-05-27', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-keys-3', '12:00', 'Parada flexível na Overseas Highway', '2026-05-27', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-keys-4', '14:00', 'Chegada à base Islamorada', '2026-05-27', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-ret-1', '09:30', 'Check-out da base Islamorada', '2026-05-30', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-ret-2', 'A definir', 'Sair de Islamorada conforme voo/retorno', '2026-05-30', TRUE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-ret-3', 'A definir', 'Chegar ao aeroporto ou próximo trecho', '2026-05-30', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-ret-4', 'A definir', 'Check-in e bagagem', '2026-05-30', FALSE);
INSERT INTO travel_timeline_items (id, time, label, date, is_departure) VALUES ('tl-ret-5', 'A definir', 'Embarque/retorno', '2026-05-30', FALSE);
