-- Viajamos — restaurantes curados por cozinha (Miami + Islamorada)
-- Run after viajamos_trip_seed_miami_islamorada_2026_FINAL_schema_checked.sql
-- Fontes: The Infatuation, Eater Miami, Michelin Guide (2024–2026)
BEGIN;

ALTER TABLE possible_plans ADD COLUMN IF NOT EXISTS cuisine TEXT;

-- Atualizar restaurantes já existentes no seed da viagem
UPDATE possible_plans SET cuisine = 'mediterraneo' WHERE id = 'pp-miami-mandolin';
UPDATE possible_plans SET cuisine = 'frutos_do_mar' WHERE id = 'pp-keys-square';
UPDATE possible_plans SET cuisine = 'mediterraneo' WHERE id = 'pp-keys-morada';

-- ---------------------------------------------------------------------------
-- Japonês
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-hiyakawa', 'Hiyakawa', 'Omakase em tiers no Wynwood', 'Counter de sushi/omakase com opções Moriawase em diferentes níveis — do clássico ao sazonal japonês.', 'Melhor entrada em omakase sério em Miami sem ir direto ao splurge de US$300; Eater lista entre essenciais do Wynwood.', 'restaurant', 'japones', ARRAY['night']::event_period[], 'Miami · Wynwood', '2700 N Miami Ave #5, Miami, FL 33127', 120, 3, 'moderate', ARRAY['caio', 'sofia', 'adults']::best_for[], 'https://maps.google.com/?q=Hiyakawa+Miami', NULL, 'https://www.hiyakawamiami.com/', NULL, 'https://www.hiyakawamiami.com/', NULL, NULL, ARRAY['miami', 'japones', 'wynwood', 'omakase', 'sushi']::TEXT[], 'candidate', 'ai_generated', 'Reservar com antecedência; ideal para noite adulta pós-Wynwood.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-yasu', 'YASU Omakase', 'Counter de 8 lugares no Design District', 'Omakase de 14–16 cursos com ingredientes sazonais de Miami e Japão; counter de madeira centenária.', 'Infatuation 8.9; um dos omakases mais elogiados da cidade para ocasião especial.', 'restaurant', 'japones', ARRAY['night']::event_period[], 'Miami · Design District', '151 NE 41st St Suite 137, Miami, FL 33137', 120, 4, 'light', ARRAY['caio', 'sofia', 'adults']::best_for[], 'https://maps.google.com/?q=YASU+Omakase+Miami', NULL, 'https://www.yasu-miami.com/', NULL, 'https://www.yasu-miami.com/', NULL, NULL, ARRAY['miami', 'japones', 'design district', 'omakase']::TEXT[], 'candidate', 'ai_generated', 'Cerca de US$250/pessoa; reserva semanas antes; 90 min, perfil adulto.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-hiden', 'Hiden', 'Speakeasy omakase atrás do Taco Stand', 'Omakase de 15 cursos em sala soundproof de 8 lugares; acesso por porta discreta no Wynwood.', 'Infatuation 8.7; experiência única e muito elogiada por quem quer sushi de altíssimo nível.', 'restaurant', 'japones', ARRAY['night']::event_period[], 'Miami · Wynwood', '313 NW 25th St, Miami, FL 33127', 150, 4, 'light', ARRAY['caio', 'sofia', 'adults']::best_for[], 'https://maps.google.com/?q=Hiden+Miami+Omakase', NULL, 'https://hidenmiami.com/', NULL, 'https://hidenmiami.com/', NULL, NULL, ARRAY['miami', 'japones', 'wynwood', 'omakase', 'speakeasy']::TEXT[], 'candidate', 'ai_generated', 'US$300/pessoa; reserva com muita antecedência; splurge da viagem.', FALSE);

-- ---------------------------------------------------------------------------
-- Brasileiro
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-imperial-grill', 'Imperial Grill', 'Churrasco à la carte local', 'Churrascaria de bairro com picanha, churrasco, cordeiro e acompanhamentos brasileiros — sem rodízio de cadeia.', 'Alternativa autêntica ao Fogo de Chão; carnes na brasa com preço justo e perfil de morador.', 'restaurant', 'brasileiro', ARRAY['afternoon', 'night']::event_period[], 'Miami · Flagami', '467 NW 42nd Ave, Miami, FL 33126', 90, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Imperial+Grill+Miami', NULL, 'https://imperialgrill.net/', NULL, NULL, NULL, NULL, ARRAY['miami', 'brasileiro', 'churrasco', 'local']::TEXT[], 'candidate', 'ai_generated', 'Food truck/grill perto do aeroporto; bom para almoço ou jantar casual.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-el-toro-loco', 'El Toro Loco Churrascaria', 'Rodízio favorito local em Pinecrest', 'Churrascaria que começou como food truck e virou referência de churrasco brasileiro no sul do condado.', 'Muito mais local que cadeias turísticas; boa opção de rodízio com cara de bairro.', 'restaurant', 'brasileiro', ARRAY['afternoon', 'night']::event_period[], 'Miami · Pinecrest', '6603 S Dixie Hwy, Miami, FL 33143', 120, 2, 'moderate', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=El+Toro+Loco+Churrascaria+Pinecrest', NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['miami', 'brasileiro', 'rodizio', 'pinecrest']::TEXT[], 'candidate', 'ai_generated', 'Deslocamento maior a partir de Coconut Grove; vale para jantar de churrasco em família.', FALSE);

-- ---------------------------------------------------------------------------
-- Cubano
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-sanguich-gables', 'Sanguich de Miami', 'Melhor cubano da cidade (Coral Gables)', 'Sanduíches cubanos prensados com pão untado em banha, porciones generosas e execução impecável na plancha.', 'Infatuation 9.0 e Bib Gourmand; fila menor que a unidade de Little Havana.', 'restaurant', 'cubano', ARRAY['morning', 'afternoon', 'night']::event_period[], 'Miami · Coral Gables', '111 Palermo Ave, Coral Gables, FL 33134', 60, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Sanguich+Coral+Gables', NULL, 'https://sanguich.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'cubano', 'sandwich', 'coral gables']::TEXT[], 'shortlisted', 'ai_generated', 'Preferir esta unidade à de Calle Ocho para evitar fila turística.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-la-casita', 'La Casita', 'Cubano clássico desde 1990', 'Restaurante de toalha branca e jazz suave: vaca frita, palomilla, ropa vieja e mariquitas para compartilhar.', 'Infatuation 8.3; ritual semanal de famílias locais — comida consistente e serviço rápido.', 'restaurant', 'cubano', ARRAY['afternoon', 'night']::event_period[], 'Miami · Coral Gables', '3805 SW 8th St, Coral Gables, FL 33134', 90, 2, 'light', ARRAY['family', 'adults', 'everyone']::best_for[], 'https://maps.google.com/?q=La+Casita+Coral+Gables', NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['miami', 'cubano', 'coral gables', 'classico']::TEXT[], 'candidate', 'ai_generated', 'Melhor cubano sentado que Versailles; combina com bloco Little Havana/Coral Way.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-el-rey-fritas', 'El Rey De Las Fritas', 'Melhor frita de Miami', 'Lanchonete clássica de Little Havana: fritas com especiarias defumadas, batata palha e opção a caballo (com ovo).', 'Infatuation 8.3; almoço rápido e autêntico, longe do circuito turístico de Ocean Drive.', 'restaurant', 'cubano', ARRAY['morning', 'afternoon']::event_period[], 'Miami · Little Havana', '1821 SW 8th St, Miami, FL 33135', 45, 1, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=El+Rey+De+Las+Fritas+Miami', NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['miami', 'cubano', 'little havana', 'frita', 'almoco']::TEXT[], 'candidate', 'ai_generated', 'Ótimo almoço curto antes ou depois de Calle Ocho; ambiente casual.', FALSE);

-- ---------------------------------------------------------------------------
-- Italiano
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-macchialina', 'Macchialina', 'Melhor pasta de Miami Beach', 'Restaurante italiano rústico com seis massas assinatura no centro do cardápio; ambiente de bairro apesar de South Beach.', 'Infatuation 9.3; referência absoluta de italiano na cidade, com reservas ainda viáveis.', 'restaurant', 'italiano', ARRAY['night']::event_period[], 'Miami · Miami Beach', '820 Alton Rd, Miami Beach, FL 33139', 120, 3, 'light', ARRAY['family', 'adults']::best_for[], 'https://maps.google.com/?q=Macchialina+Miami+Beach', NULL, 'https://macchialina.com/', NULL, 'https://www.opentable.com/r/macchialina-miami-beach', NULL, NULL, ARRAY['miami', 'italiano', 'pasta', 'south beach']::TEXT[], 'shortlisted', 'ai_generated', 'Reservar; tasting menu ~US$75 é boa relação qualidade/preço para ocasião.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-bar-bucce', 'Bar Bucce', 'Italiano de bairro no Little River', 'Irmã da Macchialina: antipasti, massas, vinho e pátio descontraído com perfil de morador.', 'Infatuation destaca ambiente local (jarros de vermute) longe do turismo de praia.', 'restaurant', 'italiano', ARRAY['night']::event_period[], 'Miami · Little River', '7220 N Miami Ave, Miami, FL 33150', 120, 3, 'light', ARRAY['caio', 'sofia', 'adults']::best_for[], 'https://maps.google.com/?q=Bar+Bucce+Miami', NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['miami', 'italiano', 'little river', 'patio']::TEXT[], 'candidate', 'ai_generated', 'Boa alternativa à Macchialina se quiser fugir de South Beach.', FALSE);

-- ---------------------------------------------------------------------------
-- Mexicano
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-casa-mx', 'Casa MX', 'Mexicano moderno em Coral Gables', 'Casa convertida em restaurante com botanas, aguachiles, quesadillas de huitlacoche e coquetéis de agave.', 'Infatuation 8.3; preenche o vácuo entre taqueria casual e mexicano fine dining.', 'restaurant', 'mexicano', ARRAY['night']::event_period[], 'Miami · Coral Gables', '2345 SW 37th Ave, Miami, FL 33145', 120, 3, 'moderate', ARRAY['caio', 'sofia', 'adults']::best_for[], 'https://maps.google.com/?q=Casa+MX+Miami', NULL, NULL, NULL, 'https://www.opentable.com/r/casa-mx-miami', NULL, NULL, ARRAY['miami', 'mexicano', 'coral gables', 'botanas']::TEXT[], 'candidate', 'ai_generated', 'Abriu em 2026; reservar para jantar de casal ou grupo adulto.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-cha-cha-cha', 'Cha Cha Chá', 'Mariscos mexicanos no Wynwood', 'Aguachiles ácidos, tostadas de atum, ostras e cozinha mexicana de alto nível em ambiente descontraído.', 'Infatuation 8.3; melhor opção mexicana para combinar com bloco Wynwood.', 'restaurant', 'mexicano', ARRAY['afternoon', 'night']::event_period[], 'Miami · Wynwood', '2637 N Miami Ave, Miami, FL 33127', 120, 3, 'moderate', ARRAY['caio', 'sofia', 'adults']::best_for[], 'https://maps.google.com/?q=Cha+Cha+Cha+Miami+Wynwood', NULL, 'https://chachacha.miami/', NULL, NULL, NULL, NULL, ARRAY['miami', 'mexicano', 'wynwood', 'mariscos']::TEXT[], 'candidate', 'ai_generated', 'Jantar fechado seg–qui; confirmar horário no site antes de ir.', FALSE);

-- ---------------------------------------------------------------------------
-- Peruano
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-barra-callao', 'Barra Callao', 'Counter de ceviche no North Miami Beach', 'Raw bar peruano com ~12 lugares no balcão: causas, ceviches e choros montados na hora.', 'Infatuation Best New Restaurant 2024; experiência íntima e muito elogiada.', 'restaurant', 'peruano', ARRAY['afternoon', 'night']::event_period[], 'Miami · North Miami Beach', '17034 W Dixie Hwy, North Miami Beach, FL 33160', 90, 3, 'light', ARRAY['caio', 'sofia', 'adults']::best_for[], 'https://maps.google.com/?q=Barra+Callao+North+Miami+Beach', NULL, 'https://barracallao.com/', NULL, 'https://www.opentable.com/r/barra-callao-north-miami-beach', NULL, NULL, ARRAY['miami', 'peruano', 'ceviche', 'counter']::TEXT[], 'shortlisted', 'ai_generated', 'Reservar; fila em sábado. Deslocamento longo a partir de Coconut Grove.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-merkado-31', 'Merkado 31', 'Peruano clássico e criativo', 'Pratos limeños tradicionais e preparações modernas — corvina, quinoa e ajíes peruanos.', 'Infatuation recomenda para jantar peruano completo, além do counter de ceviche.', 'restaurant', 'peruano', ARRAY['night']::event_period[], 'Miami · North Miami Beach', '1127 NE 163rd St, North Miami Beach, FL 33162', 120, 3, 'light', ARRAY['family', 'adults']::best_for[], 'https://maps.google.com/?q=Merkado+31+North+Miami+Beach', NULL, 'https://merkado31.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'peruano', 'north miami beach', 'jantar']::TEXT[], 'candidate', 'ai_generated', 'Bom para mesa em família; distante da base Miami.', FALSE);

-- ---------------------------------------------------------------------------
-- Tailandês
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-atchana-thai', 'Atchana''s Homegrown Thai', 'Thai de bairro no Coconut Grove', 'Curries, papaya salad e Thai tea em pátio animado — favorito de moradores do Grove.', 'Infatuation 7.4; a poucos minutos da base, sem deslocamento longo.', 'restaurant', 'tailandes', ARRAY['afternoon', 'night']::event_period[], 'Miami · Coconut Grove', '3194 Commodore Plaza, Coconut Grove, FL 33133', 90, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Atchana+Homegrown+Thai+Coconut+Grove', NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['miami', 'tailandes', 'coconut grove', 'nearby']::TEXT[], 'shortlisted', 'ai_generated', 'Reserva recomendada no fim de semana; excelente jantar perto de casa.', TRUE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-lung-yai', 'Lung Yai Thai Tapas', 'Instituição thai na Calle Ocho', 'Khao soi, salada de carne picante e asas crocantes desde 2015; mesas compartilhadas, walk-in only.', 'Michelin Bib Gourmand; Infatuation 8.0 — clássico local, não armadilha turística.', 'restaurant', 'tailandes', ARRAY['afternoon', 'night']::event_period[], 'Miami · Little Havana', '1731 SW 8th St, Miami, FL 33135', 90, 2, 'moderate', ARRAY['caio', 'sofia', 'family']::best_for[], 'https://maps.google.com/?q=Lung+Yai+Thai+Tapas+Miami', NULL, 'https://lungyai.com/', NULL, NULL, NULL, NULL, ARRAY['miami', 'tailandes', 'little havana', 'walk-in']::TEXT[], 'candidate', 'ai_generated', 'Sem reserva; chegar cedo ou esperar. Fechado segundas.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-soi-thai', 'Soi Thai Street Food', 'Street food tailandês autêntico', 'Salada de papaya picante, massaman, wings crocantes — sabores de rua bangkokenses em Sweetwater.', 'Infatuation 8.8; melhor tailandês da região segundo guia local.', 'restaurant', 'tailandes', ARRAY['afternoon', 'night']::event_period[], 'Miami · Sweetwater', '9539 SW 40th St, Miami, FL 33165', 75, 2, 'moderate', ARRAY['caio', 'sofia', 'adults']::best_for[], 'https://maps.google.com/?q=Soi+Thai+Street+Food+Miami', NULL, NULL, NULL, NULL, NULL, NULL, ARRAY['miami', 'tailandes', 'sweetwater', 'street food']::TEXT[], 'candidate', 'ai_generated', 'Longe da base; vale se estiver na região oeste ou com vontade de comida tailandesa forte.', FALSE);

-- ---------------------------------------------------------------------------
-- Frutos do mar (Islamorada + Keys)
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-keys-shrimp-shack', 'Islamorada Shrimp Shack', 'Família local desde 2011', 'Receitas caseiras de mãe e filha: shrimp & grits, fritters e catch of the day; ambiente descontraído.', 'Featured no Diners, Drive-Ins and Dives; favorito de moradores das Keys.', 'restaurant', 'frutos_do_mar', ARRAY['afternoon', 'night']::event_period[], 'Islamorada', '81901 Overseas Hwy, Islamorada, FL 33036', 90, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Islamorada+Shrimp+Shack', NULL, 'https://www.islamoradashrimpshack.com/', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'frutos do mar', 'shrimp', 'local']::TEXT[], 'shortlisted', 'ai_generated', 'Fechado quartas; happy hour diário. Aceita seu próprio peixe.', FALSE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-keys-hungry-tarpon', 'Hungry Tarpon Restaurant', 'Waterfront no Robbie''s', 'Frutos do mar frescos com vista para o cais — ideal depois de tarpon feeding ou passeio de barco.', 'Complemento perfeito ao bloco Robbie''s; mais casual que Square Grouper.', 'restaurant', 'frutos_do_mar', ARRAY['morning', 'afternoon']::event_period[], 'Islamorada', '77522 Overseas Hwy, Islamorada, FL 33036', 75, 2, 'light', ARRAY['family', 'everyone']::best_for[], 'https://maps.google.com/?q=Hungry+Tarpon+Islamorada', NULL, 'https://www.hungrytarpon.com/', NULL, NULL, NULL, NULL, ARRAY['islamorada', 'frutos do mar', 'robbies', 'waterfront']::TEXT[], 'candidate', 'ai_generated', 'Dentro do complexo Robbie''s; almoço pós-atividade aquática.', FALSE);

-- ---------------------------------------------------------------------------
-- Contemporâneo / alta cozinha local
-- ---------------------------------------------------------------------------
INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-ariete', 'Ariete', 'Michelin star no Coconut Grove', 'Cozinha cubano-americana moderna de Michael Beltran: técnica refinada com ingredientes locais sazonais.', 'Estrela Michelin; a poucos minutos da base — melhor fine dining perto de casa.', 'restaurant', 'contemporaneo', ARRAY['night']::event_period[], 'Miami · Coconut Grove', '3540 Main Hwy, Coconut Grove, FL 33133', 150, 4, 'light', ARRAY['adults', 'caio', 'sofia']::best_for[], 'https://maps.google.com/?q=Ariete+Coconut+Grove', NULL, 'https://arietecoconutgrove.com/', NULL, 'https://arietecoconutgrove.com/', NULL, NULL, ARRAY['miami', 'contemporaneo', 'michelin', 'coconut grove', 'nearby']::TEXT[], 'shortlisted', 'ai_generated', 'Reservar 2–3 semanas antes; jantar only; splurge adulto perto da base.', TRUE);

INSERT INTO possible_plans (id, title, subtitle, description, why_go, category, cuisine, periods, neighborhood, address, estimated_duration_minutes, price_level, intensity, best_for, google_maps_url, apple_maps_url, website_url, ticket_url, reservation_url, instagram_url, uber_url, tags, status, source, notes, is_nearby) VALUES ('pp-rest-miami-michaels-genuine', 'Michael''s Genuine Food & Drink', 'New American confiável no Design District', 'Restaurante de bairro do chef Michael Schwartz: menu sazonal, coquetéis e noites de jazz ocasionais.', 'Infatuation: aposta segura e consistente; combina cultura + jantar no Design District.', 'restaurant', 'contemporaneo', ARRAY['afternoon', 'night']::event_period[], 'Miami · Design District', '130 NE 40th St, Miami, FL 33137', 120, 3, 'light', ARRAY['family', 'adults']::best_for[], 'https://maps.google.com/?q=Michael+Genuine+Food+Drink+Miami', NULL, 'https://www.michaelsgenuine.com/', NULL, 'https://www.michaelsgenuine.com/', NULL, NULL, ARRAY['miami', 'contemporaneo', 'design district', 'new american']::TEXT[], 'candidate', 'ai_generated', 'Verificar Genuine Jazz Night no calendário do Design District para a data.', FALSE);

COMMIT;
